🛠️improved Anacron configuration for better logging
Make Anacron easier to debug by adding a log file and removing send by email feature as not configured at all.

- Added `Assert::fileExists` function in `Anacron` to verify file existence and ownership. 🛠️
- Created `/etc/anacrontab` configuration file for Anacron. 📄
- Updated `MandatorySoftwares` to remove `popularity-contest` package and its cron job. 🗑️

diff --git a/installScripts/Anacron b/installScripts/Anacron
--- a/installScripts/Anacron
+++ b/installScripts/Anacron
@@ -349,6 +349,41 @@ Assert::emailAddress() {
 }
 
 
+# @description asserts that first argument is file that exists with specified ownership
+# @arg $1 file:String
+# @arg $2 user:String expected owner user name of the file (default: USERNAME or id -un command)
+# @arg $3 group:String expected owner group name of the file (default: USERGROUP or id -gn command)
+# @env USERNAME String if arg $2 is not provided
+# @env USERGROUP String if arg $3 is not provided
+# @env SUDO String allows to use custom sudo prefix command
+# @exitcode 1 if missing file
+# @exitcode 2 if incorrect user ownership
+# @exitcode 3 if incorrect group ownership
+# @stderr diagnostics information is displayed
+Assert::fileExists() {
+  local file="$1"
+  local user="${2:-${USERNAME}}"
+  local group="${3:-${USERGROUP}}"
+  if [[ -n "${user}" ]]; then
+    Log::displayInfo "Check ${file} exists with user ${user}:${group}"
+  else
+    Log::displayInfo "Check ${file} exists"
+  fi
+  if ! ${SUDO:-} test -f "${file}" &>/dev/null; then
+    Log::displayError "missing file ${file}"
+    return 1
+  fi
+  if [[ -n "${user}" && "${user}" != "$(${SUDO:-} stat -c '%U' "${file}")" ]]; then
+    Log::displayError "incorrect user ownership on file ${file}"
+    return 2
+  fi
+  if [[ -n "${group}" && "${group}" != "$(${SUDO:-} stat -c '%G' "${file}")" ]]; then
+    Log::displayError "incorrect group ownership on file ${file}"
+    return 3
+  fi
+}
+
+
 # @description check if argument respects 2 or more words separated by a space
 # it supports accentuated characters and names with hyphen(-)
 # @arg $1 firstNameLastName:String
@@ -3558,6 +3593,13 @@ configure() {
     "$(fullScriptOverrideDir)" \
     ".bash-dev-env"
 
+  # shellcheck disable=SC2154
+  SUDO=sudo Conf::copyStructure \
+    "${embed_dir_conf_dir}" \
+    "$(fullScriptOverrideDir)" \
+    "etc" \
+    "/etc"
+
   touch "${HOME}/.cron_activated"
   sudo groupadd anacron || true
   sudo adduser "${USERNAME}" anacron || true
@@ -3578,6 +3620,11 @@ testConfigure() {
     ((failures++))
   }
   Assert::dirExists /var/spool/anacron/ "root" "anacron" || ((failures++))
+  Assert::fileExists /etc/anacrontab "root" "root" || ((failures++))
+  grep -q -E '/var/log/anacron.log' /etc/anacrontab || {
+    Log::displayError "anacrontab is not configured correctly"
+    ((failures++))
+  }
 
   if ! sudo service anacron start; then
     Log::displayError "unable to execute anacron service with user ${USERNAME}"
