✨ feat: Enhance shell configuration and install scripts
Updated various shell scripts and configurations to improve the development environment.

- 🐳 Added Docker configuration scripts: `docker.sh`, `docker.zsh`
- 📦 Introduced Anacron scripts: `launchAnacron.sh`, `Anacron.sh`
- 📝 Included Git default config: `git.zsh`, `GitDefaultConfig.sh`
- 🔧 Configured environment variables for Go: `golang.sh`
- 🎉 Added Krew support for kubectl plugins: `KubeDefaultConfig.sh`
- 📜 Included new utility scripts for Motd and date settings: `motd.sh`, `set_date.sh`
- 📚 Enhanced Zsh setup with new themes and plugins: `zsh-omz.zsh`, `zsh-github-copilot.zsh`
- 🔧 Configured SSH agent script: `ssh-add.sh`
- 🎨 Improved color support in shell: `colors.sh`
- 📄 Added firewall configuration script: `firewall.sh`
- 🛠️ Restructured .zshrc for better loading of aliases and plugins.

These updates streamline the setup process and enhance the user experience.

Vsode copilot instructions and configurations:
- 📝 Added commit message template at `.github/commit-template.md`
- 📝 Created commit message instructions at `.github/instructions/commit-message.instructions.md`
- 📝 Added general instructions for GitHub Copilot at `.github/instructions/general.instructions.md`
- 📝 Included GitHub workflow instructions at `.github/instructions/github-workflow.instructions.md`
- 🔧 Updated VS Code settings in `.vscode/settings.json` to include instruction files for Copilot

diff --git a/installScripts/Anacron b/installScripts/Anacron
--- a/installScripts/Anacron
+++ b/installScripts/Anacron
@@ -443,6 +443,34 @@ Assert::wsl() {
 }
 
 
+# @description Backup given file in the same directory or in BACKUP_DIR directory
+# backup file name is composed by following fields separated by -:
+#   - if BACKUP_DIR is not empty then escaped dir name separated by @
+#   - filename(without path)
+#   - date with format %Y%m%d_%H:%M:%S (Eg: 20240326_14:45:08)
+# @arg $1 file:String the file to backup
+# @stderr messages about backup file location
+# @env SUDO String allows to use custom sudo prefix command
+# @env BACKUP_DIR if not set backup the file in the same directory as original file
+# @exitcode 1 on copy failure
+Backup::file() {
+  local file="$1"
+  if [[ -f "${file}" ]]; then
+    local backupFile fileDirname escapedDirname
+    fileDirname="${file%/*}"
+    escapedDirname=${fileDirname/\//}      # remove first slash
+    escapedDirname=${escapedDirname//\//@} # replace all slashes by @
+    if [[ -z "${BACKUP_DIR:-}" ]]; then
+      backupFile="${fileDirname}/${file##*/}-$(date +"%Y%m%d_%H:%M:%S")"
+    else
+      backupFile="${BACKUP_DIR}/${escapedDirname}@${file##*/}-$(date +"%Y%m%d_%H:%M:%S")"
+    fi
+    Log::displayInfo "Backup file '${file}' to ${backupFile}"
+    ${SUDO:-} cp "${file}" "${backupFile}"
+  fi
+}
+
+
 # @description get property value from file
 # if not present compute it using propertyNotFoundCallback (if provided) and store it in property file
 # @arg $1 propertyFile:String the file in which the property will be searched
@@ -483,6 +511,35 @@ Cache::getPropertyValue2() {
 }
 
 
+# @description convert base64 encoded back to target dir
+# it is advised to include the md5sum of the binFile in the path of the target dir
+#
+# @arg $1 targetDir:string the directory in which tar archive will be untarred
+# @arg $2 base64:string the base64 encoded tar czf archive
+# @stderr diagnostics information is displayed
+Compiler::Embed::extractDirFromBase64() {
+
+  if [[ "${REQUIRE_FUNCTION_LINUX_REQUIRE_TAR_COMMAND_LOADED:-0}" != 1 ]]; then
+    echo >&2 "Requirement Linux::requireTarCommand has not been loaded"
+    exit 1
+  fi
+
+  local targetDir="$1"
+  local base64="$2"
+
+  if [[ ! -d "${targetDir}" ]]; then
+    mkdir -p "${targetDir}"
+    (
+      cd "${targetDir}" || exit 1
+      base64 -d <<<"${base64}" | tar -xzf - 2>/dev/null || {
+        Log::displayError "untar failure, invalid base64 string"
+        exit 1
+      }
+    ) || return 1
+  fi
+}
+
+
 # @description convert base64 encoded back to target file
 # if target file is executable prepend dir of target
 # file to PATH to make binary available everywhere
@@ -509,6 +566,40 @@ Compiler::Embed::extractFileFromBase64() {
 
   if [[ -x "${targetFile}" ]]; then
     Env::pathPrepend "${targetDir}"
+  fi
+}
+
+
+# @description copy folder structure to target directory
+# merge embedDir with overridden directory if provided and available
+# @arg $1 embedDir:String the path embedded
+# @arg $2 overrideDir:String the path overridden
+# @arg $3 subDir:String the sub-directory to copy from embedDir and/or overrideDir
+# @arg $4 targetDir:String the target directory (default: ${HOME}/${subDir})
+# @env SUDO String allows to use custom sudo prefix command
+# @env HOME used for default value of targetDir arg
+# @env OVERWRITE_CONFIG_FILES indicates if target directory should be overwritten if it exists
+# @env PRETTY_ROOT_DIR used to make paths relative to this directory to reduce length of messages
+# @env IGNORE_MISSING_SOURCE_DIR
+Conf::copyStructure() {
+  local embedDir="$1"
+  local overrideDir="$2"
+  local subDir="$3"
+  local targetDir="${4:-${HOME}/${subDir}}"
+
+  local configDir
+  # shellcheck disable=SC2154
+  configDir="$(Conf::getOverriddenDir "${embedDir}" "${overrideDir}")"
+  if [[ -d "${configDir}/${subDir}" ]]; then
+    # shellcheck disable=SC2154
+    OVERWRITE_CONFIG_FILES=${OVERWRITE_CONFIG_FILES:-1} \
+      PRETTY_ROOT_DIR="${embedDir%/*}" \
+      Install::structure "${configDir}/${subDir}" "${targetDir}"
+  elif [[ "${IGNORE_MISSING_SOURCE_DIR:-0}" = "1" ]]; then
+    return 0
+  else
+    Log::displayError "Directory ${subDir} does not exists in '${embedDir}' or '${overrideDir}'"
+    return 1
   fi
 }
 
@@ -1261,6 +1352,224 @@ Framework::createTempFile() {
 }
 
 
+# @description installs file to given directory
+#
+# callbacks parameters `${fromFile} ${targetFile} $@`
+# @arg $1 fromFile - original file to copy
+# @arg $2 targetFile - target file
+# @arg $3 userName:String (optional) (default: ${USERNAME}) the user name that will be used to set target files ownership
+# @arg $4 userGroup:String (optional) (default: ${USERNAME}) the group name that will be used to set target files ownership
+# @arg $5 successCallback:Function the callback to call when file is installed successfully, by default setUserRights callback is called
+# @arg $6 failureCallback:Function the callback to call when file installation has failed, by default unableToCopyCallback callback is called
+# @arg $@ callbacksParams:String[] additional parameters passed to callbacks
+# @exitcode 1 if fromFile is not readable
+# @exitcode 2 if backup file failure
+# @exitcode 3 if copy failure
+# @exitcode 0 on success or if OVERWRITE_CONFIG_FILES=0
+# @exitcode 0 on success or if CHANGE_WINDOWS_FILES=0 and target file is a windows file
+# @env OVERWRITE_CONFIG_FILES Boolean (default:0) if 1 will overwrite existing directory
+# @env CHANGE_WINDOWS_FILES Boolean (default:0) if 1 and target file is in windows file system, overwrite it
+# @env USERNAME (default: root) the user name that will be used to set target files ownership
+# @env USERGROUP (default: root) the group name that will be used to set target files ownership
+# @env BASE_MNT_C String windows C drive base PATH
+# @env FRAMEWORK_ROOT_DIR used to make paths relative to this directory to reduce length of messages
+# @env SUDO String allows to use custom sudo prefix command
+# @env BACKUP_BEFORE_INSTALL Boolean (default: 1) backup file before installing the file
+Install::file() {
+  local fromFile="$1"
+  local targetFile="$2"
+  local userName="${3:-${USERNAME:-root}}"
+  local userGroup="${4:-${USERGROUP:-root}}"
+  local successCallback=${5:-Install::setUserRightsCallback}
+  local failureCallback=${6:-Install::unableToCopyCallback}
+  shift 6 || true
+
+  if [[ ! -f "${fromFile}" || ! -r "${fromFile}" ]]; then
+    Log::displayError "cannot read source file '${fromFile}'"
+    return 1
+  fi
+
+  # skip if OVERWRITE_CONFIG_FILES is 0 and target file exists
+  if [[ "${OVERWRITE_CONFIG_FILES}" = "0" && -f "${targetFile}" ]]; then
+    Log::displayWarning "File '${targetFile}' exists - Skip install (because OVERWRITE_CONFIG_FILES=0 in .env file)"
+    return 0
+  fi
+
+  # skip if CHANGE_WINDOWS_FILES is 0 and target dir is c drive
+  if [[ "${CHANGE_WINDOWS_FILES}" = "0" && "${targetFile}" =~ ^${BASE_MNT_C} ]]; then
+    Log::displayWarning "File '${targetFile}' - Skip install (because CHANGE_WINDOWS_FILES=0 in .env file)"
+    return 0
+  fi
+
+  local targetDir="${targetFile%/*}"
+  if ! ${SUDO} test -d "${targetDir}"; then
+    ${SUDO:-} mkdir -p "${targetDir}"
+    ${SUDO:-} chown "${userName}":"${userGroup}" "${targetDir}"
+  fi
+  local fromDir="${fromFile%/*}"
+  local fromFilename="${fromFile##*/}"
+
+  local prettyFromDir
+  # shellcheck disable=SC2295
+  prettyFromDir="${fromDir#${PRETTY_ROOT_DIR:-${FRAMEWORK_ROOT_DIR}}/}"
+  if diff -q "${fromFile}" "${targetFile}" &>/dev/null; then
+    Log::displayStatus "No changes detected. No need to update '${targetFile}' from '${prettyFromDir}/${fromFilename}'"
+    return 0
+  fi
+
+  if [[ "${BACKUP_BEFORE_INSTALL:-1}" = "1" ]]; then
+    Backup::file "${targetFile}" || return 2
+  fi
+
+  if ${SUDO:-} cp "${fromFile}" "${targetFile}"; then
+    # shellcheck disable=SC2295
+    Log::displaySuccess "Installed file '${targetFile}' from '${prettyFromDir}/${fromFilename}'"
+    ${successCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${prettyFromDir}" "${fromFilename}"
+  else
+    # shellcheck disable=SC2295
+    Log::displayError "unable to copy file '${targetFile}' from '${fromDir#${FRAMEWORK_ROOT_DIR}/}/${fromFilename}'"
+    ${failureCallback} "${fromFile}" "${targetFile}" "${userName}" "${userGroup}" "${prettyFromDir}" "${fromFilename}"
+    return 3
+  fi
+}
+
+
+# @description install callback
+#   set file with root ownership and execution bit
+# @arg $1 fromFile:String
+# @arg $2 targetFile:String
+# @arg $3 userName:String (optional) (default: ${USERNAME}) the user name that will be used to set target files ownership
+# @arg $4 userGroup:String (optional) (default: ${USERNAME}) the group name that will be used to set target files ownership
+# @env USERNAME (default: root) the user name that will be used to set target files ownership
+# @env USERGROUP (default: root) the group name that will be used to set target files ownership
+# @env SUDO String allows to use custom sudo prefix command
+# @exitcode 1 on any failure
+# @see Install::file
+Install::setUserRightsCallback() {
+  # shellcheck disable=SC2034 # $1 not used
+  local fromFile="$1"
+  local targetFile="$2"
+  local userName="${3:-${USERNAME:-root}}"
+  local userGroup="${4:-${USERGROUP:-root}}"
+
+  ${SUDO:-} chown "${userName}":"${userGroup}" "${targetFile}"
+}
+
+
+# @description install dir to given directory but backup it before
+# @arg $1 fromDir:String the source base directory
+# @arg $2 toDir:String the target base directory
+# @env OVERWRITE_CONFIG_FILES Boolean (default:0) if 1 will overwrite existing files
+# @env CHANGE_WINDOWS_FILES Boolean (default:0) if 1 and target directory is in windows file system, overwrite it
+# @env USERNAME (default: ${USERNAME} if SUDO empty else root) the user name that will be used to set target files ownership
+# @env USERGROUP (default: ${USERGROUP} if SUDO empty else root) the group name that will be used to set target files ownership
+# @env BASE_MNT_C String windows C drive base PATH
+# @env PRETTY_ROOT_DIR used to make paths relative to this directory to reduce length of messages
+# @env SUDO String allows to use custom sudo prefix command
+# @env BACKUP_BEFORE_INSTALL Boolean (default:1) backup directory before installing the dir
+# @exitcode 1 if source directory is not readable
+# @exitcode 2 if error during structure replication
+# @exitcode 2 if error during file copy
+# @exitcode 0 if copy successful
+# @exitcode 0 with warning message if CHANGE_WINDOWS_FILES=0 and target directory in C drive
+# @stderr diagnostics information is displayed, skipped information if OVERWRITE_CONFIG_FILES or CHANGE_WINDOWS_FILES are set to 1
+Install::structure() {
+  local fromDir="$1"
+  local toDir="$2"
+  local userName="root"
+  local userGroup="root"
+  if [[ -z "${SUDO:-}" ]]; then
+    userName="${USERNAME:-root}"
+    userGroup="${USERGROUP:-root}"
+  fi
+
+  if [[ ! -d "${fromDir}" || ! -r "${fromDir}" ]]; then
+    Log::displayError "Install::structure - cannot read source directory '${fromDir}'"
+    return 1
+  fi
+
+  # skip if CHANGE_WINDOWS_FILES is 0 and target dir is c drive
+  if [[ "${CHANGE_WINDOWS_FILES:-0}" = "0" && "${toDir}" =~ ^${BASE_MNT_C:-/mnt/c} ]]; then
+    Log::displayWarning "Install::structure - Directory '${fromDir}' - Skip install (because CHANGE_WINDOWS_FILES=0 in .env file)"
+    return 0
+  fi
+
+  # first replicate directory structure
+  # shellcheck disable=SC2317
+  createStructure() {
+    local dir="$1"
+    if ! ${SUDO} test -d "${dir}"; then
+      if ! ${SUDO:-} mkdir -p "${dir}"; then
+        Log::displayError "Install::structure - impossible to create directory '${dir}'"
+        exit 1
+      fi
+    fi
+
+    if ! ${SUDO:-} chown "${userName}":"${userGroup}" "${dir}"; then
+      Log::displayError "Install::structure - impossible to update directory owner '${dir}' with ${userName}:${userGroup}"
+      exit 1
+    fi
+  }
+  local dir
+
+  (
+    local dir
+    shopt -s lastpipe
+    # -links 2 allows to exclude empty directories
+    ${SUDO:-} find "${fromDir}" -depth -type d -links 2 -print0 |
+      while read -rd '' dir; do
+        if ! createStructure "${toDir}/${dir#"${fromDir}"}"; then
+          # error already reported by createStructure
+          exit 1
+        fi
+      done || {
+      if [[ "${PIPESTATUS[0]}" != "0" ]]; then
+        Log::displayError "Install::structure - replicated directory structure - find directories on '${fromDir}' resulted in an error"
+        exit 2
+      fi
+    }
+  ) || return 2
+
+  # for each file, copy it
+  (
+    local file
+    shopt -s lastpipe
+    ${SUDO:-} find "${fromDir}" -depth -type f -print0 |
+      while read -rd '' file; do
+        local localFile="${file#"${fromDir}/"}"
+        if ! Install::file "${fromDir}/${localFile}" "${toDir}/${localFile}"; then
+          # error already reported by Install::file
+          exit 1
+        fi
+      done || {
+      if [[ "${PIPESTATUS[0]}" != "0" ]]; then
+        Log::displayError "Install::structure - replicated file structure - find files on '${fromDir}' resulted in an error"
+        exit 2
+      fi
+    }
+  ) || return 3
+
+  # shellcheck disable=SC2295
+  Log::displaySuccess "Installed directory '${toDir#${PRETTY_ROOT_DIR}/}' from '${fromDir#${PRETTY_ROOT_DIR}/}'"
+}
+
+
+# @description install callback
+#   default callback used called when file copy has failed
+# @arg $1 fromFile:String
+# @arg $2 targetFile:String
+# @env FRAMEWORK_ROOT_DIR used to make paths relative to this directory to reduce length of messages
+# @exitcode 1 always fail
+# @stderr diagnostics information is displayed
+# @see Install::file
+Install::unableToCopyCallback() {
+  local fromDir="$1"
+  local fileName="$2"
+  local targetFile="$3"
+  Log::fatal "unable to copy file '${fromDir#"${FRAMEWORK_ROOT_DIR}/"}/${fileName}' to '${targetFile}'"
+}
+
+
 # @description the command launch different actions(install, configure, test)
 # depending on the options selected
 # @env SKIP_INSTALL
@@ -1813,6 +2122,8 @@ Linux::getDistributorId() {
 # @exitcode 1 if tar command not available
 # @stderr diagnostics information is displayed
 Linux::requireTarCommand() {
+  export REQUIRE_FUNCTION_LINUX_REQUIRE_TAR_COMMAND_LOADED=1
+
   Assert::commandExists tar
 }
 
@@ -1928,6 +2239,33 @@ Log::displaySkipped() {
     echo -e "${__SKIPPED_COLOR}SKIPPED - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
   fi
   Log::logSkipped "$1"
+}
+
+
+# @description Display message using info color (blue) but warning level
+# @arg $1 message:String the message to display
+# @env DISPLAY_DURATION int (default 0) if 1 display elapsed time information between 2 info logs
+# @env LOG_CONTEXT String allows to contextualize the log
+Log::displayStatus() {
+  local type="${2:-STATUS}"
+  if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_WARNING)); then
+    Log::computeDuration
+    echo -e "${__INFO_COLOR}${type}  - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
+  fi
+  Log::logStatus "$1" "${type}"
+}
+
+
+# @description Display message using success color (bg green/fg white)
+# @arg $1 message:String the message to display
+# @env DISPLAY_DURATION int (default 0) if 1 display elapsed time information between 2 info logs
+# @env LOG_CONTEXT String allows to contextualize the log
+Log::displaySuccess() {
+  if ((BASH_FRAMEWORK_DISPLAY_LEVEL >= __LEVEL_INFO)); then
+    Log::computeDuration
+    echo -e "${__SUCCESS_COLOR}SUCCESS - ${LOG_CONTEXT:-}${LOG_LAST_DURATION_STR:-}${1}${__RESET_COLOR}" >&2
+  fi
+  Log::logSuccess "$1"
 }
 
 
@@ -2077,6 +2415,24 @@ Log::logMessage() {
 Log::logSkipped() {
   if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
     Log::logMessage "${2:-SKIPPED}" "$1"
+  fi
+}
+
+
+# @description log message to file
+# @arg $1 message:String the message to display
+Log::logStatus() {
+  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_WARNING)); then
+    Log::logMessage "${2:-STATUS}" "$1"
+  fi
+}
+
+
+# @description log message to file
+# @arg $1 message:String the message to display
+Log::logSuccess() {
+  if ((BASH_FRAMEWORK_LOG_LEVEL >= __LEVEL_INFO)); then
+    Log::logMessage "${2:-SUCCESS}" "$1"
   fi
 }
 
@@ -3015,6 +3371,13 @@ commandOptionParseFinished() {
 }
 
 
+Linux::requireTarCommand
+Compiler::Embed::extractDirFromBase64 \
+  "${PERSISTENT_TMPDIR:-/tmp}/40394586bf162a63d17a955d01289374835e0c372061e6b9f84b394129569676/conf_dir" \
+  "H4sIAAAAAAAA/+zSz0oDMRAG8D3nKcYqvSWZBZcePHkQvIgPUIqkyawJlAnk30V8d9kWFHqzHqSQ32UgOQzf8Km9yV46apK46cCFkrElNFJOH0xl6x/Z2BRZZT9cCBFxM03HiYjnE8efv9P7uLkfpwHw0oW/UXMxacA/7zoPdyVub3TNSe8Da+IGSxuECDNstyAjHOJ7YFivQc6wuvt4fn15+tRqqcPbsSWmkFvBbvcAxRMLgFxdhEypBUtgTs2B5cJFzEH8d9iu67ru21cAAAD//5aGrAsACAAA"
+
+declare -gx embed_dir_conf_dir="${PERSISTENT_TMPDIR:-/tmp}/40394586bf162a63d17a955d01289374835e0c372061e6b9f84b394129569676/conf_dir"
+
 
 helpDescription() {
   echo "$(scriptName) - runs commands periodically"
@@ -3061,6 +3424,13 @@ testInstall() {
 }
 
 configure() {
+  # shellcheck disable=SC2154
+  Conf::copyStructure \
+    "${embed_dir_conf_dir}" \
+    "$(fullScriptOverrideDir)" \
+    ".bash-dev-env"
+
+  touch "${HOME}/.cron_activated"
   sudo groupadd anacron || true
   sudo adduser "${USERNAME}" anacron || true
   sudo chown root:anacron /var/spool/anacron/
diff --git a/installScripts/KubeDefaultConfig b/installScripts/KubeDefaultConfig
--- a/installScripts/KubeDefaultConfig
+++ b/installScripts/KubeDefaultConfig
@@ -3912,10 +3912,10 @@ commandOptionParseFinished() {
 
 Linux::requireTarCommand
 Compiler::Embed::extractDirFromBase64 \
-  "${PERSISTENT_TMPDIR:-/tmp}/54c2f2db1f70294999f74b3026129308b3f83a02e276e8fc67c30055017b4875/conf_dir" \
-  "H4sIAAAAAAAA/+yWf2ubThjA87ev4kkN5Fv4Gk8SDXTLWNc4KmxNoJbCYhhGz96R8xTvlC2vfuhcsmZkKdhfAz9/RLk7nieXPJ/nbrDyBdFCXGiYF3qQxCnDkiZcDEJ9na9wINlgI0inCQghNDbN6okQ2n8iYzjavlfjhmUi1AHUKOsDyYX0sw5qnGt/c/8IalfPRaavKNcxL2AjiKLQCBYL6AVJHPs8FIu6DpawXL4BSTBXAESSZwGGt//Vk7ArnTLIqRJR5aX31nKc+/5TLnHmB5IWuPZfS4VRrWmQ45j/pmXu+2+1/j8Pardyv/yHFfVxUVSYzuBq5oI9ddz/wb10ruGj88mGi/Mr+GDDzXx67tpTuHXcy9mNWy51LuxH/xp1P9Mi0JNUVlWdCmNX3YL83thUQTBjAcHBum5yEz3Ehc5zxnZ971AkBWB+bUz6Cy9/7xHwbqFXdcivqTBOl14P+q+sMR7zv/Hh/wD/h5a15785tszW/+fgwPkvv6dYYFlKs6GcSni3lWBrys8Jlgc0hBCnkkwMYIkfAqN3RGpxEmKIkgw8BQAg9te43+36jPoCqs9JH2afv8zPzn5dIf6y0Jdl5JNjt46TexG/1RF3Y6Wlr0zAF2ZQ/ix6kPCI3j1VjtIHazQ66P8f74YxtMat/y0tLS1PyY8AAAD///ftkV8AEgAA"
+  "${PERSISTENT_TMPDIR:-/tmp}/e5a99c60982110bc848bb020c1ba7b484d2672f7dd7081284cc6fc095a86dd80/conf_dir" \
+  "H4sIAAAAAAAA/+yWcW+aQBTA+zef4qkkrsmAYxVM3FzWVRbN1mJamiZT01A4yqUIhDtcp/G7L8eYThZnE1rbJvz+EALP97z4fu9OvrGpL7l4JuFwpjjRNA4wI1FIZVe5S2+wwwJ5Tv2DMiCEUFvTsitCqHhF6lFrdZ89V3UNoQNApao+kJQyOzlApWsVF/dKaNSUlCbKDQkVHM5gTn1BIB6MRiA60XRqhy4d5X0wgcnkPTAfhwIAjdLEwfDhTf4S1q3DkxwKHhGee20Vu9n0n4QMJ7bDyAzn/ksxVbOYEjV2+a/pWtF/vfJ/PzRqmfv8HxYaj4vQgJ4JZ6YFRm9gvQWrP7iAL4NvBpwcn8FnAy6HvWPL6MHVwOqblxYPHZwYj/4z8nkmeaBEMcu6Oqbqurup//dga1AfB4HjY+cuH3JdxcUzJUyDYD33tmUSAIYXarc5Gqefxj6Mr0DMJuR1TNXDyViE5gsbjLv8L735P8D/I10v+K+1da3yfx9s2f/ZzxhTzLg0cxISBh9XEqxM+f0iSB3igotj5ndVCCLbhYDc+kyaRi4GL0pgLAAATO073KzV7IDYFLLPbhPM0+/DTufPEeI/gTbjmeu7Th31jYz3ecb1M27pCxPwmdn0P04ijwSZ+wn+IZdXP2Pn+V9VC/632u9alf/7oOA/1x/fx1HCYHhs9bt1cfH13Li6PjdNqyOJi755aiwVmXfHkn+pIy543LJeKfU6kflYVJwo9MjtU9XgPuit1lb//7lX1SO9XflfUVFR8ZT8CgAA//8ezq7+ABYAAA=="
 
-declare -gx embed_dir_conf_dir="${PERSISTENT_TMPDIR:-/tmp}/54c2f2db1f70294999f74b3026129308b3f83a02e276e8fc67c30055017b4875/conf_dir"
+declare -gx embed_dir_conf_dir="${PERSISTENT_TMPDIR:-/tmp}/e5a99c60982110bc848bb020c1ba7b484d2672f7dd7081284cc6fc095a86dd80/conf_dir"
 
 
 kubeBeforeParseCallback() {
@@ -3948,6 +3948,11 @@ fortunes() {
   if command -v lazydocker &>/dev/null; then
     echo -e "${__INFO_COLOR}$(scriptName)${__RESET_COLOR} -- you can use ${__HELP_EXAMPLE}lazydocker${__RESET_COLOR} to navigate through your containers."
     echo -e "Lazydocker is a simple terminal UI for both ${__HELP_EXAMPLE}docker${__RESET_COLOR} and ${__HELP_EXAMPLE}docker-compose${__RESET_COLOR}, written in Go."
+    echo "%"
+  fi
+  if command -v krew &>/dev/null; then
+    echo -e "${__INFO_COLOR}$(scriptName)${__RESET_COLOR} -- you can use ${__HELP_EXAMPLE}krew${__RESET_COLOR} to manage kubectl plugins."
+    echo -e "discover kubectl plugins ${__HELP_EXAMPLE}https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/${__RESET_COLOR}"
     echo "%"
   fi
   if command -v k9s &>/dev/null; then
@@ -4008,6 +4013,27 @@ installKubectl() {
     sudo chmod +x /tmp/kubectl
     sudo mv /tmp/kubectl /usr/local/bin/kubectl
   fi
+}
+
+installKrew() {
+  Log::displayInfo "Installing krew"
+  (
+    set -x -o errexit -o pipefail
+    trap 'rm -rf "${tempDir}" || true' EXIT
+    # shellcheck source=/dev/null
+    tempDir="$(mktemp -d)"
+    cd "${tempDir}" || exit 1
+    OS="$(uname | tr '[:upper:]' '[:lower:]')"
+    ARCH="$(uname -m | sed \
+      -e 's/x86_64/amd64/' \
+      -e 's/\(arm\)\(64\)\?.*/\1\2/' \
+      -e 's/aarch64$/arm64/')"
+    KREW="krew-${OS}_${ARCH}"
+    export OS ARCH KREW
+    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz"
+    tar zxvf "${KREW}.tar.gz"
+    "./${KREW}" install krew
+  )
 }
 
 installKind() {
@@ -4090,6 +4116,10 @@ install() {
     Log::displayError "Error during k9s install"
     return 1
   }
+  installKrew || {
+    Log::displayError "Error during krew install"
+    return 1
+  }
   Log::displayInfo "Installing kube-linter"
   (
     # shellcheck source=/dev/null
@@ -4162,6 +4192,10 @@ configure() {
       --region "${KUBE_CONFIG_REGION_CODE}" \
       --name "${KUBE_CONFIG_CLUSTER_ARN}" || return 1
   fi
+  # shellcheck source=src/_installScripts/_Configs/KubeDefaultConfig-conf/.bash-dev-env/profile.d/krew.sh
+  source "${HOME}/.bash-dev-env/profile.d/krew.sh" || return 1
+  kubectl krew install explore
+  kubectl krew update
 }
 
 testConfigure() {
