✨ feat: Enhance JavaSdkManager to install latest Temurin Java version
Improved the install function in JavaSdkManager.sh to automatically install the latest Temurin Java version if none is currently installed.

- Added check for existing Java installation.
- Implemented logging for installation status.
- Retrieved the latest Temurin Java version using sdkman.
- Updated error handling for version retrieval failure.

📦 File affected: src/_installScripts/Java/JavaSdkManager.sh

diff --git a/installScripts/JavaSdkManager b/installScripts/JavaSdkManager
--- a/installScripts/JavaSdkManager
+++ b/installScripts/JavaSdkManager
@@ -3609,7 +3609,17 @@ install() {
     # shellcheck source=/dev/null
     source "${HOME}/.sdkman/bin/sdkman-init.sh"
     sdk selfupdate force
-    yes | sdk install java || true # exit code of sdk is not reliable
+    if ! sdk current java &>/dev/null; then
+      Log::displayInfo "No java version installed, installing latest Temurin Java"
+
+      # Temurin Java is the version used by Eclipse
+      local latestTemuJavaVersion
+      latestTemuJavaVersion="$(sdk list java | grep -E 'tem' | head -n 1 | awk '{print $9}')" || {
+        Log::displayError "Failed to get latest Temurin Java version"
+        return 1
+      }
+      yes | sdk install java "${latestTemuJavaVersion}" || true # exit code of sdk is not reliable
+    fi
     # exit code can be different than 0 when java already installed
     if ! command -v java &>/dev/null; then
       Log::displayError "java not installed, check above logs"
